import turtle

turtle.bgcolor("black")
turtle.pencolor("blue")
turtle.pensize(5)
turtle.speed(0)

turtle.begin_fill()
turtle.fillcolor("yellow")
turtle.forward(200)
turtle.penup()
turtle.right(180)
turtle.forward(30)
turtle.pendown()
turtle.right(90)
turtle.forward(25)
turtle.circle(70, 180)
turtle.forward(25)
turtle.end_fill()

turtle.begin_fill()
turtle.fillcolor("red")
turtle.right(180)
turtle.forward(25)
turtle.right(90)
turtle.forward(140)
turtle.right(90)
turtle.forward(25)
turtle.right(90)
turtle.forward(140)
turtle.end_fill()

turtle.left(90)

turtle.begin_fill()

turtle.fillcolor("skyblue")
turtle.left(3)
turtle.forward(70)
turtle.left(45)
turtle.forward(55)

turtle.penup()
turtle.right(180)
turtle.forward(55)
turtle.right(45)
turtle.forward(70)
turtle.right(93)
turtle.forward(140)
turtle.right(90)
turtle.pendown()

turtle.right(3)
turtle.forward(70)
turtle.right(45)
turtle.forward(55)
turtle.right(30)
turtle.forward(20)
turtle.right(10)
turtle.forward(10)
turtle.right(10)
turtle.forward(10)
turtle.right(10)
turtle.forward(15)
turtle.right(3)

turtle.penup()
turtle.right(20)
turtle.forward(52)
turtle.right(50)
turtle.forward(70)
turtle.right(93)
turtle.pendown()

turtle.end_fill()

turtle.penup()
turtle.forward(30)
turtle.right(90)
turtle.forward(10)
turtle.right(90)
turtle.pendown()

turtle.begin_fill()
turtle.fillcolor("white")
turtle.circle(20)
turtle.end_fill()

turtle.penup()
turtle.right(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(78)
turtle.right(90)
turtle.forward(15)
turtle.right(90)
turtle.pendown()

turtle.begin_fill()
turtle.fillcolor("white")
turtle.circle(20)
turtle.end_fill()

turtle.penup()
turtle.left(90)
turtle.forward(40)
turtle.left(110)
turtle.forward(18)
turtle.left(90)
turtle.forward(19)
turtle.pendown()

turtle.begin_fill()
turtle.fillcolor("black")
turtle.circle(10)
turtle.end_fill()

turtle.penup()
turtle.left(70)
turtle.forward(88)
turtle.left(90)
turtle.right(90)
turtle.pendown()

turtle.begin_fill()
turtle.fillcolor("black")
turtle.circle(10)
turtle.end_fill()

turtle.penup()
turtle.left(90)
turtle.forward(95)
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.right(180)
turtle.pendown()

turtle.forward(25)

turtle.penup()
turtle.right(180)
turtle.forward(50)
turtle.right(90)
turtle.forward(60)
turtle.right(80)
turtle.forward(15)
turtle.pendown()

turtle.forward(35)
turtle.right(70)
turtle.forward(20)

for i in range(3):
    turtle.right(20)
    turtle.forward(20)

turtle.begin_fill()
turtle.fillcolor("red")
turtle.left(50)
turtle.forward(100)
turtle.left(120)
turtle.forward(100)
turtle.left(40)
turtle.forward(50)
turtle.left(5)
turtle.forward(70)
turtle.left(40)
turtle.forward(100)
turtle.left(120)
turtle.forward(95)

turtle.end_fill()

turtle.penup()
turtle.right(80)
turtle.forward(75)
turtle.left(120)
turtle.pendown()

turtle.pencolor("red")
turtle.circle(-30, 40)

turtle.penup()
turtle.left(80)
turtle.forward(10)
turtle.right(80)
turtle.pendown()

turtle.pencolor("white")
turtle.left(30)
for i in range(5):
    turtle.forward(10)
    turtle.right(5)


turtle.left(110)

turtle.begin_fill()
turtle.fillcolor("white")
for i in range(17):
    turtle.forward(4)
    turtle.left(10)

turtle.end_fill()

turtle.done()
